import os
import uuid
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
from typing import List, Dict

app = FastAPI(title="Ninite-Style Builder API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----- Static catalog (representative sample similar to ninite categories) -----
CATALOG: Dict[str, List[str]] = {
    "Web Browsers": [
        "Chrome", "Firefox", "Edge", "Brave", "Opera"
    ],
    "Messaging": [
        "Discord", "Skype", "Slack", "Zoom", "Telegram"
    ],
    "Media": [
        "VLC", "iTunes", "Spotify", "Kodi", "foobar2000"
    ],
    "Runtimes": [
        ".NET", "Java", "Python", "AdoptOpenJDK", "Visual C++ Redistributable"
    ],
    "Imaging": [
        "GIMP", "Paint.NET", "IrfanView", "ShareX", "Inkscape"
    ],
    "Documents": [
        "SumatraPDF", "Foxit Reader", "LibreOffice", "Notepad++", "VS Code"
    ],
    "Security": [
        "Malwarebytes", "Avast", "AVG", "AdwCleaner", "KeePass"
    ],
    "File Sharing": [
        "qBittorrent", "Deluge", "Transmission"
    ],
    "Utilities": [
        "7-Zip", "WinDirStat", "Everything", "TeamViewer", "PuTTY"
    ],
    "Compression": [
        "7-Zip", "PeaZip", "WinRAR"
    ],
    "Developer Tools": [
        "Git", "Node.js", "Postman", "Docker Desktop"
    ],
}

# In-memory builds store (no persistence required for this demo)
BUILDS: Dict[str, List[str]] = {}


class BuildRequest(BaseModel):
    apps: List[str]


@app.get("/")
def read_root():
    return {"message": "Ninite-style Backend is running"}


@app.get("/api/apps")
def get_apps():
    """Return the catalog grouped by category."""
    return {"categories": CATALOG}


@app.post("/api/build")
def build_installer(req: BuildRequest):
    if not req.apps:
        raise HTTPException(status_code=400, detail="No apps selected")

    # Deduplicate and validate
    selected = []
    valid_set = {app for apps in CATALOG.values() for app in apps}
    for a in req.apps:
        if a in valid_set and a not in selected:
            selected.append(a)

    if not selected:
        raise HTTPException(status_code=400, detail="Selections not recognized")

    build_id = str(uuid.uuid4())
    BUILDS[build_id] = selected
    download_url = f"/api/download/{build_id}"
    return {"id": build_id, "download_url": download_url}


# Known installers with stable URLs and silent flags
# Note: URLs can change over time; these represent commonly used sources.
APP_INSTALLERS: Dict[str, Dict[str, str]] = {
    # Browsers
    "Chrome": {
        "url": "https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi",
        "type": "msi",
        "silent": "/i \"{file}\" /qn /norestart",
    },
    "Firefox": {
        "url": "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US",
        "type": "exe",
        "silent": "/S",
    },
    # Utilities
    "7-Zip": {
        "url": "https://www.7-zip.org/a/7z2408-x64.exe",
        "type": "exe",
        "silent": "/S",
    },
    "VLC": {
        "url": "https://get.videolan.org/vlc/last/win64/vlc-3.0.20-win64.exe",
        "type": "exe",
        "silent": "/S",
    },
    # Editors / Tools
    "Notepad++": {
        "url": "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/latest/download/npp.x64.Installer.exe",
        "type": "exe",
        "silent": "/S",
    },
    "VS Code": {
        "url": "https://update.code.visualstudio.com/latest/win32-x64-user/stable",
        "type": "exe",
        "silent": "/VERYSILENT /NORESTART /MERGETASKS=!runcode",
    },
    "Git": {
        "url": "https://github.com/git-for-windows/git/releases/latest/download/Git-64-bit.exe",
        "type": "exe",
        "silent": "/VERYSILENT /NORESTART",
    },
    "Node.js": {
        "url": "https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi",
        "type": "msi",
        "silent": "/i \"{file}\" /qn /norestart",
    },
}


def generate_powershell_script(apps: List[str]) -> str:
    """Create a PowerShell script that downloads and installs selected apps silently where supported."""
    lines: List[str] = []

    # Preamble and helpers
    lines += [
        "# Installer generated by Ninite-style builder",
        "# This script downloads vendor installers and runs them silently when supported.",
        "# Run from an elevated PowerShell for best results.",
        "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12",
        "",
        "function Invoke-FileDownload {",
        "  param([string]$Url, [string]$OutputPath)",
        "  try {",
        "    Write-Host \"Downloading: $Url\" -ForegroundColor Cyan",
        "    Invoke-WebRequest -Uri $Url -OutFile $OutputPath -UseBasicParsing",
        "    return $true",
        "  } catch {",
        "    Write-Warning (\"Failed to download: $Url - \" + $_.Exception.Message)",
        "    return $false",
        "  }",
        "}",
        "",
        "function Install-ExeSilent {",
        "  param([string]$ExePath, [string]$Args)",
        "  Write-Host (\"Installing \" + $ExePath + \" ...\") -ForegroundColor Green",
        "  $p = Start-Process -FilePath $ExePath -ArgumentList $Args -PassThru -Wait -NoNewWindow",
        "  if ($p.ExitCode -ne 0) { Write-Warning (\"Installer returned code \" + $p.ExitCode) }",
        "}",
        "",
        "function Install-MsiSilent {",
        "  param([string]$MsiPath)",
        "  Write-Host (\"Installing MSI \" + $MsiPath + \" ...\") -ForegroundColor Green",
        "  $args = \"/i `\"$MsiPath`\" /qn /norestart\"",
        "  $p = Start-Process -FilePath msiexec.exe -ArgumentList $args -PassThru -Wait -NoNewWindow",
        "  if ($p.ExitCode -ne 0) { Write-Warning (\"MSI returned code \" + $p.ExitCode) }",
        "}",
        "",
        "$downloads = Join-Path $env:TEMP 'ninite-demo-downloads'",
        "New-Item -ItemType Directory -Force -Path $downloads | Out-Null",
        "",
    ]

    # Selected apps list
    ps_apps_list = ", ".join([f'\"{a}\"' for a in apps])
    lines += [
        f"$apps = @({ps_apps_list})",
        "Write-Host (\"Selected apps: \" + ($apps -join ', ')) -ForegroundColor Yellow",
        "",
    ]

    # Per-app handling
    for app in apps:
        meta = APP_INSTALLERS.get(app)
        safe_name = app.replace(" ", "_")
        lines.append(f"# --- {app} ---")
        if meta is None:
            lines += [
                f"Write-Warning \"{app} is not yet supported for automated install in this demo.\"",
                "Start-Sleep -Milliseconds 300",
                "",
            ]
            continue

        url = meta["url"]
        ftype = meta["type"].lower()
        # Determine output file extension
        ext = ".msi" if ftype == "msi" else ".exe"
        lines += [
            f"$url = \"{url}\"",
            f"$out = Join-Path $downloads '{safe_name}{ext}'",
            "if (Invoke-FileDownload -Url $url -OutputPath $out) {",
        ]
        if ftype == "msi":
            lines += [
                "  Install-MsiSilent -MsiPath $out",
                "} else {",
                "  Write-Warning 'Skipping install due to download failure.'",
                "}",
                "",
            ]
        else:
            # For EXE, inject silent args
            silent_args = meta["silent"].replace("{file}", "$out")
            # Ensure arguments are passed as a single string
            lines += [
                f"  Install-ExeSilent -ExePath $out -Args \"{silent_args}\"",
                "} else {",
                "  Write-Warning 'Skipping install due to download failure.'",
                "}",
                "",
            ]

    lines += [
        "Write-Host 'All done!' -ForegroundColor Green",
    ]

    return "\n".join(lines)


@app.get("/api/download/{build_id}", response_class=PlainTextResponse)
def download_script(build_id: str):
    apps = BUILDS.get(build_id)
    if not apps:
        raise HTTPException(status_code=404, detail="Build not found or expired")

    script = generate_powershell_script(apps)
    headers = {"Content-Disposition": "attachment; filename=Install-Silent-Demo.ps1"}
    return PlainTextResponse(script, headers=headers)


@app.get("/test")
def test_database():
    """Test endpoint to check if database is available and accessible"""
    response = {
        "backend": "✅ Running",
        "database": "❌ Not Available",
        "database_url": None,
        "database_name": None,
        "connection_status": "Not Connected",
        "collections": []
    }

    try:
        from database import db
        if db is not None:
            response["database"] = "✅ Available"
            response["database_url"] = "✅ Configured"
            response["database_name"] = db.name if hasattr(db, 'name') else "✅ Connected"
            response["connection_status"] = "Connected"
            try:
                collections = db.list_collection_names()
                response["collections"] = collections[:10]
                response["database"] = "✅ Connected & Working"
            except Exception as e:
                response["database"] = f"⚠️  Connected but Error: {str(e)[:50]}"
        else:
            response["database"] = "⚠️  Available but not initialized"
    except ImportError:
        response["database"] = "❌ Database module not found (run enable-database first)"
    except Exception as e:
        response["database"] = f"❌ Error: {str(e)[:50]}"

    response["database_url"] = "✅ Set" if os.getenv("DATABASE_URL") else "❌ Not Set"
    response["database_name"] = "✅ Set" if os.getenv("DATABASE_NAME") else "❌ Not Set"
    return response


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
