import os
import uuid
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
from typing import List, Dict

app = FastAPI(title="Ninite-Style Builder API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----- Static catalog (representative sample similar to ninite categories) -----
CATALOG: Dict[str, List[str]] = {
    "Web Browsers": [
        "Chrome", "Firefox", "Edge", "Brave", "Opera"
    ],
    "Messaging": [
        "Discord", "Skype", "Slack", "Zoom", "Telegram"
    ],
    "Media": [
        "VLC", "iTunes", "Spotify", "Kodi", "foobar2000"
    ],
    "Runtimes": [
        ".NET", "Java", "Python", "AdoptOpenJDK", "Visual C++ Redistributable"
    ],
    "Imaging": [
        "GIMP", "Paint.NET", "IrfanView", "ShareX", "Inkscape"
    ],
    "Documents": [
        "SumatraPDF", "Foxit Reader", "LibreOffice", "Notepad++", "VS Code"
    ],
    "Security": [
        "Malwarebytes", "Avast", "AVG", "AdwCleaner", "KeePass"
    ],
    "File Sharing": [
        "qBittorrent", "Deluge", "Transmission"
    ],
    "Utilities": [
        "7-Zip", "WinDirStat", "Everything", "TeamViewer", "PuTTY"
    ],
    "Compression": [
        "7-Zip", "PeaZip", "WinRAR"
    ],
    "Developer Tools": [
        "Git", "Node.js", "Postman", "Docker Desktop"
    ],
}

# In-memory builds store (no persistence required for this demo)
BUILDS: Dict[str, List[str]] = {}


class BuildRequest(BaseModel):
    apps: List[str]


@app.get("/")
def read_root():
    return {"message": "Ninite-style Backend is running"}


@app.get("/api/apps")
def get_apps():
    """Return the catalog grouped by category."""
    return {"categories": CATALOG}


@app.post("/api/build")
def build_installer(req: BuildRequest):
    if not req.apps:
        raise HTTPException(status_code=400, detail="No apps selected")

    # Deduplicate and validate
    selected = []
    valid_set = {app for apps in CATALOG.values() for app in apps}
    for a in req.apps:
        if a in valid_set and a not in selected:
            selected.append(a)

    if not selected:
        raise HTTPException(status_code=400, detail="Selections not recognized")

    build_id = str(uuid.uuid4())
    BUILDS[build_id] = selected
    download_url = f"/api/download/{build_id}"
    return {"id": build_id, "download_url": download_url}


@app.get("/api/download/{build_id}", response_class=PlainTextResponse)
def download_script(build_id: str):
    apps = BUILDS.get(build_id)
    if not apps:
        raise HTTPException(status_code=404, detail="Build not found or expired")

    # Generate a Windows PowerShell script that prints steps.
    # This is a demo script, not a real silent installer like Ninite.
    lines = [
        "# Demo installer generated by Ninite-style builder",
        "# This script does not install software; it demonstrates the flow.",
        "# To perform real installs, integrate vendor installers with silent flags.",
        "$apps = @(" + ", ".join([f'\"{a}\"' for a in apps]) + ")",
        "Write-Host \"Preparing to install: $($apps -join ', ')\" -ForegroundColor Cyan",
        "foreach ($app in $apps) {",
        "  Write-Host (\"Downloading and installing \" + $app + \"...\") -ForegroundColor Green",
        "  Start-Sleep -Milliseconds 500",
        "}",
        "Write-Host 'All done! (demo)' -ForegroundColor Yellow",
    ]
    script = "\n".join(lines)
    headers = {"Content-Disposition": "attachment; filename=Install-Demo.ps1"}
    return PlainTextResponse(script, headers=headers)


@app.get("/test")
def test_database():
    """Test endpoint to check if database is available and accessible"""
    response = {
        "backend": "✅ Running",
        "database": "❌ Not Available",
        "database_url": None,
        "database_name": None,
        "connection_status": "Not Connected",
        "collections": []
    }

    try:
        from database import db
        if db is not None:
            response["database"] = "✅ Available"
            response["database_url"] = "✅ Configured"
            response["database_name"] = db.name if hasattr(db, 'name') else "✅ Connected"
            response["connection_status"] = "Connected"
            try:
                collections = db.list_collection_names()
                response["collections"] = collections[:10]
                response["database"] = "✅ Connected & Working"
            except Exception as e:
                response["database"] = f"⚠️  Connected but Error: {str(e)[:50]}"
        else:
            response["database"] = "⚠️  Available but not initialized"
    except ImportError:
        response["database"] = "❌ Database module not found (run enable-database first)"
    except Exception as e:
        response["database"] = f"❌ Error: {str(e)[:50]}"

    response["database_url"] = "✅ Set" if os.getenv("DATABASE_URL") else "❌ Not Set"
    response["database_name"] = "✅ Set" if os.getenv("DATABASE_NAME") else "❌ Not Set"
    return response


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
